ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "gallery" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "petType" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "optionType" TEXT NOT NULL DEFAULT 'size';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "optionLabel" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "capacities" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "colorVariants" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "optionVariants" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shippingReturns" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "returnPolicies" TEXT;
