ALTER TABLE "StoreSettings"
  ADD COLUMN IF NOT EXISTS "mobileAppEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "appStoreUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "playStoreUrl" TEXT;
